### ISSUE TITLE
Line 159&184 undefined: http.ErrUseLastResponse

### ISSUE THREAD

**Issue by fuuddanni** [m4ll0k/Aron#1]
Hi m4llok, i don´t know much about "GO" and if i´ve it installed it correctly. 
go get github.com/m4ll0k/printer is installed. Are there any other unmatched libraries?
I´m looking at the source Code and tried to install with go get "++and the Headers", but don´t get any Output. Can you give me an Advice how to solve with my Windows Machine. 

My Go Version: go version go1.5.1 windows/amd64
![screenshot-www kitploit com-2018 08 12-05-23-39](https://user-images.githubusercontent.com/6312269/43998249-8cc3bd8c-9df1-11e8-9fec-9c74649d4e6a.png)

Thx you.

**Comment by m4ll0k** [comment]
Aron need go version >= 1.7.x

**Comment by fuuddanni** [comment]
Okay thank you very much. "GO" doesn´t have the ability to Update on the fly, which means i have to reinstall it? I´m right or is there a Version Management?
